name: Validate Twitch Token
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1.1.1
      with:
        args: -H "Authorization: OAuth 5u5evma2iv3rt34kblycykm60olvkl" https://id.twitch.tv/oauth2/validate
